import { defineArrayMember, defineField, defineType } from "sanity";
import { linkRegel } from "./objekte";

/**
 * Seitenbausteine (Page Builder). Begrenzter Satz; die Kundin ordnet Bausteine im Studio um, ohne CSS oder IDs zu berühren.
 * Jeder Baustein hat optional Anker (Sprungziel), Kurzzeile, Titel. Feldnamen = lib/content/types.ts.
 */
const basis = [
  defineField({ name: "titel", title: "Titel", type: "string" }),
  defineField({ name: "kurzzeile", title: "Kurzzeile über dem Titel", type: "string", description: "Sparsam einsetzen – höchstens jeder dritte Abschnitt." }),
  defineField({ name: "anker", title: "Sprungziel (Anker)", type: "slug", description: "z. B. «ablauf» → /seite/#ablauf. Nur Kleinbuchstaben, Ziffern, Bindestriche.", validation: (r) => r.custom((s) => !s?.current || /^[a-z0-9-]+$/.test(s.current) || "Nur Kleinbuchstaben, Ziffern und Bindestriche.") }),
];
const einleitung = defineField({ name: "einleitung", title: "Einleitung", type: "text", rows: 3 });
const ref = (name: string, title: string, to: string, beschreibung: string) =>
  defineField({ name, title, type: "array", of: [defineArrayMember({ type: "reference", to: [{ type: to }] })], description: beschreibung });
const vorschau = (name: string) => ({ select: { titel: "titel" }, prepare: ({ titel }: { titel?: string }) => ({ title: titel || name, subtitle: name }) });

export const bausteine = [
  defineType({ name: "textBaustein", title: "Text", type: "object", fields: [...basis, defineField({ name: "inhalt", title: "Text", type: "richText", validation: (r) => r.required() }), defineField({ name: "bild", title: "Bild neben dem Text", type: "bild" }), defineField({ name: "bildPosition", title: "Bild links/rechts", type: "string", options: { list: ["links", "rechts"], layout: "radio" }, initialValue: "rechts" }), defineField({ name: "breite", title: "Spaltenbreite", type: "string", options: { list: [{ title: "Schmal (Lesetext)", value: "schmal" }, { title: "Normal", value: "normal" }], layout: "radio" } })], preview: vorschau("Text") }),
  defineType({ name: "spaltenBaustein", title: "Spalten", type: "object", fields: [...basis, einleitung, defineField({ name: "spalten", title: "Spalten", type: "array", of: [defineArrayMember({ type: "object", name: "spalte", fields: [defineField({ name: "titel", title: "Titel", type: "string", validation: (r) => r.required() }), defineField({ name: "inhalt", title: "Text", type: "richText", validation: (r) => r.required() })], preview: { select: { title: "titel" } } })], validation: (r) => r.required().min(2).max(4) })], preview: vorschau("Spalten") }),
  defineType({ name: "hinweisBaustein", title: "Hinweisbox", type: "object", fields: [...basis, defineField({ name: "inhalt", title: "Text", type: "richText", validation: (r) => r.required() }), defineField({ name: "art", title: "Art", type: "string", options: { list: [{ title: "Information", value: "info" }, { title: "Wichtig", value: "wichtig" }, { title: "Medizinischer Hinweis", value: "medizinisch" }], layout: "radio" }, initialValue: "info", validation: (r) => r.required() })], preview: vorschau("Hinweisbox") }),
  defineType({ name: "leistungenBaustein", title: "Leistungen", type: "object", fields: [...basis, einleitung, ref("leistungen", "Leistungen", "leistung", "Leer = alle Leistungen."), defineField({ name: "darstellung", title: "Darstellung", type: "string", options: { list: [{ title: "Karten mit Bild", value: "karten" }, { title: "Kompakte Liste", value: "liste" }], layout: "radio" }, initialValue: "karten", validation: (r) => r.required() })], preview: vorschau("Leistungen") }),
  defineType({ name: "kombinationenBaustein", title: "Kombipakete", type: "object", fields: [...basis, einleitung, ref("kombinationen", "Kombipakete", "kombination", "Leer = alle Kombipakete."), defineField({ name: "mitEinzelpreisen", title: "Einzelpreise und Differenz anzeigen", type: "boolean", initialValue: true, description: "Die Differenz erscheint nur, wenn alle Einzelpreise fix auf der Preisliste stehen." })], preview: vorschau("Kombipakete") }),
  defineType({ name: "preistafelBaustein", title: "Preistafel", type: "object", fields: [...basis, einleitung, defineField({ name: "aktion", title: "Aktion markieren", type: "reference", to: [{ type: "aktion" }] }), defineField({ name: "fussnoten", title: "Fussnoten", type: "array", of: [defineArrayMember({ type: "string" })], description: "z. B. Hinweise zu unbestätigten Preisen." }), defineField({ name: "mitZahlungsarten", title: "Zahlungsmöglichkeiten anzeigen", type: "boolean", initialValue: true })], preview: vorschau("Preistafel") }),
  defineType({ name: "aktionBaustein", title: "Aktion", type: "object", fields: [...basis, defineField({ name: "aktion", title: "Aktion", type: "reference", to: [{ type: "aktion" }], validation: (r) => r.required() })], preview: vorschau("Aktion") }),
  defineType({ name: "ablaufBaustein", title: "Ablauf (Schritte)", type: "object", fields: [...basis, einleitung, defineField({ name: "schritte", title: "Schritte", type: "array", of: [defineArrayMember({ type: "object", name: "schritt", fields: [defineField({ name: "titel", title: "Titel", type: "string", validation: (r) => r.required() }), defineField({ name: "text", title: "Text", type: "text", rows: 3, validation: (r) => r.required() }), defineField({ name: "bild", title: "Bild", type: "bild" })], preview: { select: { title: "titel", media: "bild" } } })], validation: (r) => r.required().min(2) }), defineField({ name: "abschluss", title: "Abschlusssatz (z. B. Gesamtdauer «ca.»)", type: "string" })], preview: vorschau("Ablauf") }),
  defineType({ name: "faqBaustein", title: "Fragen & Antworten", type: "object", fields: [...basis, einleitung, defineField({ name: "fragen", title: "Fragen", type: "array", of: [defineArrayMember({ type: "object", name: "frage", fields: [defineField({ name: "frage", title: "Frage", type: "string", validation: (r) => r.required() }), defineField({ name: "antwort", title: "Antwort", type: "richText", validation: (r) => r.required() })], preview: { select: { title: "frage" } } })], validation: (r) => r.required().min(1) })], preview: vorschau("Fragen & Antworten") }),
  defineType({ name: "vergleichBaustein", title: "Gegenüberstellung", type: "object", fields: [...basis, einleitung, defineField({ name: "spalten", title: "Spalten", type: "array", of: [defineArrayMember({ type: "object", name: "vergleichSpalte", fields: [defineField({ name: "titel", title: "Titel", type: "string", validation: (r) => r.required() }), defineField({ name: "untertitel", title: "Untertitel", type: "string" }), defineField({ name: "punkte", title: "Punkte", type: "array", of: [defineArrayMember({ type: "string" })], validation: (r) => r.required().min(1) }), defineField({ name: "hervorgehoben", title: "Hervorheben", type: "boolean", initialValue: false })], preview: { select: { title: "titel" } } })], validation: (r) => r.required().min(2).max(3) }), defineField({ name: "fazit", title: "Fazit", type: "text", rows: 2 })], preview: vorschau("Gegenüberstellung") }),
  defineType({ name: "stufenBaustein", title: "Stufen (z. B. Phasen)", type: "object", fields: [...basis, einleitung, defineField({ name: "stufen", title: "Stufen", type: "array", of: [defineArrayMember({ type: "object", name: "stufe", fields: [defineField({ name: "titel", title: "Titel", type: "string", validation: (r) => r.required() }), defineField({ name: "untertitel", title: "Untertitel", type: "string" }), defineField({ name: "bild", title: "Grafik", type: "bild" }), defineField({ name: "anzeichen", title: "Anzeichen", type: "array", of: [defineArrayMember({ type: "string" })] }), defineField({ name: "massnahmen", title: "Massnahmen", type: "array", of: [defineArrayMember({ type: "string" })] })], preview: { select: { title: "titel", media: "bild" } } })], validation: (r) => r.required().min(2) })], preview: vorschau("Stufen") }),
  defineType({ name: "teamBaustein", title: "Team", type: "object", fields: [...basis, einleitung, ref("team", "Teammitglieder", "teammitglied", "Leer = alle.")], preview: vorschau("Team") }),
  defineType({ name: "kundenmeinungenBaustein", title: "Kundenmeinungen", type: "object", fields: [...basis, einleitung, ref("meinungen", "Kundenmeinungen", "kundenmeinung", "Leer = alle."), defineField({ name: "darstellung", title: "Darstellung", type: "string", options: { list: [{ title: "Wand (viele)", value: "wand" }, { title: "Zitate (wenige)", value: "zitate" }], layout: "radio" }, initialValue: "wand", validation: (r) => r.required() }), defineField({ name: "quellenHinweis", title: "Quellenhinweis unter dem Abschnitt", type: "text", rows: 2 })], preview: vorschau("Kundenmeinungen") }),
  defineType({ name: "galerieBaustein", title: "Bildergalerie", type: "object", fields: [...basis, einleitung, defineField({ name: "bilder", title: "Bilder", type: "array", of: [defineArrayMember({ type: "bild" })], validation: (r) => r.required().min(1) }), defineField({ name: "hinweis", title: "Hinweis unter der Galerie", type: "string" })], preview: vorschau("Bildergalerie") }),
  defineType({ name: "bildBaustein", title: "Einzelbild", type: "object", fields: [...basis, defineField({ name: "bild", title: "Bild", type: "bild", validation: (r) => r.required() }), defineField({ name: "text", title: "Bildunterschrift", type: "string" })], preview: { select: { title: "text", media: "bild" }, prepare: ({ title, media }) => ({ title: title || "Einzelbild", media }) } }),
  defineType({ name: "fallbeispieleBaustein", title: "Fallbeispiele (Bildreihen)", type: "object", fields: [...basis, defineField({ name: "einleitung", title: "Einleitung", type: "richText", validation: (r) => r.required() }), defineField({ name: "beschriftungen", title: "Beschriftung je Bildposition", type: "array", of: [defineArrayMember({ type: "string" })], validation: (r) => r.required().min(1).max(4) }), defineField({ name: "faelle", title: "Fälle", type: "array", of: [defineArrayMember({ type: "object", name: "fall", fields: [defineField({ name: "titel", title: "Titel", type: "string", validation: (r) => r.required() }), defineField({ name: "bilder", title: "Bilder (Reihenfolge = Beschriftungen)", type: "array", of: [defineArrayMember({ type: "bild" })], validation: (r) => r.required().min(2).max(4) })], preview: { select: { title: "titel" } } })], validation: (r) => r.required().min(1) }), defineField({ name: "hinweis", title: "Hinweis (Einzelfall, Bildrechte)", type: "text", rows: 2 })], preview: vorschau("Fallbeispiele") }),
  defineType({ name: "aufrufBaustein", title: "Handlungsaufforderung", type: "object", fields: [...basis, defineField({ name: "text", title: "Text", type: "text", rows: 2 }), defineField({ name: "knopf", title: "Knopf", type: "link", validation: (r) => r.required() }), defineField({ name: "zweiterKnopf", title: "Zweiter Knopf", type: "link" }), defineField({ name: "variante", title: "Darstellung", type: "string", options: { list: [{ title: "Oranges Band", value: "band" }, { title: "Karte", value: "karte" }], layout: "radio" }, initialValue: "karte", validation: (r) => r.required() })], preview: vorschau("Handlungsaufforderung") }),
  defineType({ name: "fragebogenBaustein", title: "Fragebogen (Anzeige)", type: "object", fields: [...basis, defineField({ name: "fragebogen", title: "Fragebogen", type: "reference", to: [{ type: "fragebogen" }], validation: (r) => r.required() })], preview: vorschau("Fragebogen") }),
  defineType({ name: "fragebogenListeBaustein", title: "Fragebogen-Übersicht", type: "object", fields: [...basis, einleitung], preview: vorschau("Fragebogen-Übersicht") }),
  defineType({ name: "karteBaustein", title: "Standortkarte (nach Einwilligung)", type: "object", fields: [...basis, defineField({ name: "text", title: "Text", type: "text", rows: 2 })], preview: vorschau("Standortkarte") }),
  defineType({ name: "videoBaustein", title: "Video (YouTube, nach Einwilligung)", type: "object", fields: [...basis, defineField({ name: "youtubeId", title: "YouTube-Video-ID", type: "string", description: "Nur die ID (z. B. bs4Tqt-Zh54), nicht die ganze Adresse.", validation: (r) => r.required().regex(/^[\w-]{6,20}$/, { name: "Video-ID", invert: false }) }), defineField({ name: "videoTitel", title: "Titel des Videos", type: "string", validation: (r) => r.required() }), defineField({ name: "text", title: "Text", type: "text", rows: 2 })], preview: vorschau("Video") }),
  defineType({ name: "downloadsBaustein", title: "Downloads", type: "object", fields: [...basis, einleitung, ref("downloads", "Downloads", "download", "Leer = alle.")], preview: vorschau("Downloads") }),
  defineType({ name: "kontaktBaustein", title: "Kontakt", type: "object", fields: [...basis, einleitung, defineField({ name: "mitFormular", title: "Mit «E-Mail vorbereiten»-Formular", type: "boolean", initialValue: true }), defineField({ name: "mitKarte", title: "Mit Standortkarte (nach Einwilligung)", type: "boolean", initialValue: true }), defineField({ name: "anfahrt", title: "Anfahrt", type: "richText" }), defineField({ name: "anfahrtBilder", title: "Bilder zur Anfahrt", type: "array", of: [defineArrayMember({ type: "bild" })] })], preview: vorschau("Kontakt") }),
  defineType({ name: "rechtstextBaustein", title: "Rechtstext", type: "object", fields: [...basis, defineField({ name: "rechtstext", title: "Rechtstext", type: "reference", to: [{ type: "rechtstext" }], validation: (r) => r.required() })], preview: vorschau("Rechtstext") }),
  defineType({ name: "zahlungsartenBaustein", title: "Zahlungsmöglichkeiten", type: "object", fields: [...basis, einleitung], preview: vorschau("Zahlungsmöglichkeiten") }),
  defineType({ name: "ratgeberListeBaustein", title: "Ratgeber-Übersicht", type: "object", fields: [...basis, einleitung, ref("seiten", "Ratgeberseiten", "seite", "Leer = alle Seiten der Art «Ratgeber».")], preview: vorschau("Ratgeber-Übersicht") }),
  defineType({ name: "medienstimmenBaustein", title: "Medienstimmen", type: "object", fields: [...basis, einleitung], preview: vorschau("Medienstimmen") }),
  defineType({ name: "linkkartenBaustein", title: "Verweiskarten", type: "object", fields: [...basis, einleitung, defineField({ name: "karten", title: "Karten", type: "array", of: [defineArrayMember({ type: "object", name: "linkkarte", fields: [defineField({ name: "titel", title: "Titel", type: "string", validation: (r) => r.required() }), defineField({ name: "text", title: "Text", type: "text", rows: 3, validation: (r) => r.required() }), defineField({ name: "link", title: "Link", type: "link", validation: (r) => r.required() }), defineField({ name: "bild", title: "Bild", type: "bild" }), defineField({ name: "preisChf", title: "Preis in CHF (optional)", type: "number", validation: (r) => r.integer().positive() }), defineField({ name: "preisPraefix", title: "Präfix vor dem Preis (z. B. «ab»)", type: "string" })], preview: { select: { title: "titel", media: "bild" } } })], validation: (r) => r.required().min(1).max(6) }), defineField({ name: "spalten", title: "Spalten", type: "number", options: { list: [2, 3] }, initialValue: 3 })], preview: vorschau("Verweiskarten") }),
  defineType({ name: "kennzahlenBaustein", title: "Kennzahlen (aus Praxisdaten)", type: "object", fields: [...basis, einleitung], preview: vorschau("Kennzahlen") }),
  defineType({ name: "datenschutzEinstellungenBaustein", title: "Datenschutz-Einstellungen (Widerruf)", type: "object", fields: [...basis, einleitung], preview: vorschau("Datenschutz-Einstellungen") }),
];

export const bausteinMitglieder = bausteine.map((b) => defineArrayMember({ type: b.name }));
export { linkRegel };
